### ISSUE TITLE
iOS 'module not found'

### ISSUE THREAD

**Issue by vwalsh** [deckameron/Ti.Android.Onesignal#1]
Hello,

Your readme describes iphone/iOS as working, but the following error is found when compiling or attempting to include your module. How do you get iPhone working with this?

`[WARN]  Could not find a valid Titanium module id=ti.android.onesignal version=latest platform=ios deploy-type=development

[ERROR] Could not find all required Titanium Modules:

[ERROR]    id: ti.android.onesignal	 version: latest	 platform: ios	 deploy-type: development`

**Comment by deckameron** [comment]
Hi @vwalsh,
I am sorry, but this was an error on the readme. This module is not available for iOS, but only for Android. My bad! :-( 

If you need an iOS solution, please consider taking a look at [William Rijksen OneSignal module](https://github.com/williamrijksen/com.williamrijksen.onesignal).
